hp: !!python/object:anypinn.core.config.PINNHyperparameters
  criterion: mse
  early_stopping: null
  fields_config: !!python/object:anypinn.core.config.MLPConfig
    activation: tanh
    encode: null
    hidden_layers:
    - 64
    - 128
    - 128
    - 64
    in_dim: 26
    out_dim: 1
    output_activation: null
  gradient_clip_val: 0.5
  lr: 0.001
  max_epochs: 3000
  optimizer: null
  params_config: !!python/object:anypinn.core.config.ScalarConfig
    init_value: 0.5
  scheduler: !!python/object:anypinn.core.config.CosineAnnealingConfig
    T_max: 1500
    eta_min: 1.0e-06
  smma_stopping: !!python/object:anypinn.core.config.SMMAStoppingConfig
    lookback: 100
    threshold: 0.005
    window: 20
  training_data: !!python/object:anypinn.core.config.GenerationConfig
    args_to_train: {}
    batch_size: 128
    collocation_sampler: uniform
    collocation_seed: null
    collocations: 8000
    data_ratio: 2
    noise_level: 0
    x: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYCwAAADM0Mjc2ODQ0NzM2cQJYAwAAAGNwdXEDSzJOdHEEUS6AAl1xAFgLAAAAMzQyNzY4
        NDQ3MzZxAWEuMgAAAAAAAAAAAAAABS+nPAUvJz2Ixno9BS+nPcb60D2Ixvo9JEkSPgUvJz7mFDw+
        xvpQPqfgZT6Ixno+NNaHPiRJkj4VvJw+BS+nPvWhsT7mFLw+1ofGPsb60D63bds+p+DlPpdT8D6I
        xvo+vJwCPzTWBz+tDw0/JUkSP52CFz8VvBw/jfUhPwUvJz9+aCw/9qExP27bNj/mFDw/Xk5BP9aH
        Rj9OwUs/x/pQPz80Vj+3bVs/L6dgP6fgZT8fGms/mFNwPxCNdT+Ixno/AACAPw==
    - 0
    - !!python/tuple
      - 50
    - !!python/tuple
      - 1
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
