name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code snippet or steps that reproduce the issue.
      placeholder: |
        ```python
        import anypinn
        # ...
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include the full traceback if applicable.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Run `uv run python -c "import anypinn, torch; print(anypinn.__version__, torch.__version__)"` and paste the output.
      placeholder: |
        anypinn: x.y.z
        torch: x.y.z
        Python: x.y.z
        OS: macOS / Linux / Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or related issues.
