name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this feature solve? What use case does it enable?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like and how it should work.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the library does this relate to?
      options:
        - "core (Problem, Constraint, Field, Parameter)"
        - "lightning (PINNModule, callbacks)"
        - "problems (ODE, PDE constraints)"
        - "catalog (SIR, SEIR, etc.)"
        - "cli (anypinn create)"
        - "docs"
        - "other"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches or workarounds you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, references, or related issues.
